"""add onboarding fields

Revision ID: c01f2afdae89
Revises: caade6268d59
Create Date: 2026-06-25 11:16:14.811443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01f2afdae89'
down_revision: Union[str, Sequence[str], None] = 'caade6268d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column(
    "users",
    sa.Column(
        "onboarding_completed",
        sa.Boolean(),
        server_default=sa.text("false"),
        nullable=False,
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'country')
    op.drop_column('users', 'role')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
